# Name(s)
**Parker Mitchell**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

<ol>
    <li>More details about editing shortcuts and the editing modes of the J notebook (even though some were outlined</li>
    <li>Why notebooks are often chosen to be used mainly in the data science field</li>
    <li>Other notebook shortcuts and general tips for improving productivity/efficiency</li>
</ol>

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [110]:
# YOUR SOLUTION HERE
import numpy as np

a = np.full((6, 4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [111]:
# YOUR SOLUTION HERE
b = np.ones((6, 4), dtype=int)
np.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [112]:
# YOUR SOLUTION HERE
print('a * b (element wise multiplication):\n')
print(a * b)
print('\n np.dot(a, b) (dot product)\n')
print(np.dot(a, b))

a * b (element wise multiplication):

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]

 np.dot(a, b) (dot product)



ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

a*b is element by element, not the dot product. The number of columns in the first matrix (columns = 4) is not equal to the number of rows in the second matrix (rows = 6). The inners should match in order for you to be able to multiply matrices.

## Exercise 4

In [113]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(), b))
print()
print(np.dot(a, b.transpose()))

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]

[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


The results are different shapes due to the dimensions of the matrices that were multiplied. The first time we do the dot product, matrix 'a' is a 6x4 transposed to a 4x6. Matrix 'b' is a 6x4 still. The outers are the dimensions that will make up the dot product of these two matrices, so it will be a 4x4 matrix.

For the second dot product, 'a' is a 6x4 matrix and 'b' is transposed to a 4x6 matrix. Looking at the outers, we can see that the dot product should produce a 6x6 matrix, which it does as shown by the second matrix.

## Exercise 5 ##

In [114]:
# YOUR SOLUTION HERE
def print_stuff(string):
    print(string)

print_stuff("hello world")

hello world


## Exercise 6 ##

In [115]:
# YOUR SOLUTION HERE
def do_array_stuff():
    c = np.arange(5)
    d = np.arange(0, 100, 3)
    e = np.zeros((3, 4), dtype=int)
    f = np.arange(10).reshape(5,2)
    print(c)
    print()
    print(d)
    print()
    print(e)
    print()
    print(f)
    
    print("\nArray c dimensions: %d" % np.ndim(c))
    print("\nArray d size: %d" % np.size(d))
    print("\nArray f sum: %d" % np.sum(f))
    print("\nArray f size: %d" % np.size(f))
    print("\nArray f average: %.2f" % (np.sum(f) / np.size(f)))
    
    
do_array_stuff()

[0 1 2 3 4]

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Array c dimensions: 1

Array d size: 34

Array f sum: 45

Array f size: 10

Array f average: 4.50


## Exercise 7

In [116]:
# YOUR SOLUTION HERE
e = np.arange(9).reshape(3, 3)
e[1][0] = 1
e[2][2] = 1

print(e)
print()

def thing1(e):
    count = 0
    for row in e.shape[0]:
        for col in e.shape[1]:
            if e[row][col] == 1:
                count += 1

print('Manual count of number of ones:', count)
print()
x = np.where(e == 1)
print(x)
print("Count of 1's using 'where':", len(x[0]))


[[0 1 2]
 [1 4 5]
 [6 7 1]]

Manual count of number of ones: 3

(array([0, 1, 2]), array([1, 0, 2]))
Count of 1's using 'where': 3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [117]:
# YOUR SOLUTION HERE
import pandas as pd
import numpy as np

a = pd.DataFrame(np.full((6, 4), 2))
a

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [118]:
# YOUR SOLUTION HERE
b = pd.DataFrame(np.full((6, 4), 1))
np.fill_diagonal(b.values, 3)
b

0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [119]:
# YOUR SOLUTION HERE

print('a * b (element wise multiplication):\n')
print(a * b)
print('\n a.dot(b) (dot product)\n')
print(a.dot(b))

a * b (element wise multiplication):

   0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2

 a.dot(b) (dot product)



ValueError: matrices are not aligned

The number of columns in the first matrix (columns = 4) is not equal to the number of rows in the second matrix (rows = 6). The inners should match in order for you to be able to multiply matrices.

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [120]:
# YOUR SOLUTION HERE
e = np.arange(9).reshape(3, 3)
f = pd.DataFrame(e)
e[1][0] = 1
e[2][2] = 1

print(e)
print()
def thing2(e):
    count = 0
    for row in e.shape[0]:
        for col in e.shape[1]:
            if e.iloc[row, col] == 1:
                count += 1

print('Manual count of number of ones:', count)
print()
x = np.where(e == 1)
print(x)
print("Count of 1's using 'where':", len(x[0]))

[[0 1 2]
 [1 4 5]
 [6 7 1]]

Manual count of number of ones: 3

(array([0, 1, 2]), array([1, 0, 2]))
Count of 1's using 'where': 3


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [121]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [122]:
## YOUR SOLUTION HERE
titanic_df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13 ##
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [123]:
## YOUR SOLUTION HERE

# NOTE: .set_index was giving me a weird error saying that column 'sex' didn't exist, so I reset titanic_df
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df.set_index('sex',inplace=True)
titanic_df.loc['female']

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [124]:
## YOUR SOLUTION HERE
titanic_df.reset_index()

sex  pclass  survived  \
0     female       1         1   
1       male       1         1   
2     female       1         0   
3       male       1         0   
4     female       1         0   
...      ...     ...       ...   
1304  female       3         0   
1305  female       3         0   
1306    male       3         0   
1307    male       3         0   
1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]